### ISSUE TITLE
The latest changes/commits broke everything

### ISSUE THREAD

**Issue by CristiVlad25** [sullivan-sean/chat-langchainjs#2]
I installed everything as instructed on february 17 and it worked. I removed the entire project from my VPS and reinstalled again with the latest commits and now it's completely broken.

event - compiled client and server successfully in 236 ms (166 modules)
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
TypeError: Cannot read properties of null (reading 'useContext')
    at Object.useContext (/root/out/SecGPT/chat-langchainjs/node_modules/react/cjs/react.development.js:1618:21)
    at Head (webpack-internal:///../../../../usr/local/lib/node_modules/next/dist/shared/lib/head.js:136:34)
    at renderWithHooks (/usr/local/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (/usr/local/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5731:15)

and it goes on forever

**Comment by CristiVlad25** [comment]
Also, when it worked and I trained/ingest other data, it didnt respond based on my data and it kept referencing back to langchain documentation.
