### ISSUE TITLE
python3 ingest.py: ModuleNotFoundError: No module named 'unstructured'

### ISSUE THREAD

**Issue by peterpme** [sullivan-sean/chat-langchainjs#5]
Hi there!

Trying to get this running locally and keep hitting:

```
 python3 ingest.py
Traceback (most recent call last):
  File "/Users/peter/Projects/langchain-projects/chat-langchainjs/ingest/ingest.py", line 3, in <module>
    from langchain.document_loaders import ReadTheDocsLoader
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/document_loaders/__init__.py", line 22, in <module>
    from langchain.document_loaders.powerpoint import UnstructuredPowerPointLoader
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/document_loaders/powerpoint.py", line 5, in <module>
    from unstructured.__version__ import __version__ as __unstructured_version__
ModuleNotFoundError: No module named 'unstructured'
```

python3 installed via homebrew
pip3 install -r requirements.txt

Am I forgetting to do something? Thank you!

**Comment by fraserxu** [comment]
`pip install unstructured` fixed the issue for me

**Comment by sullivan-sean** [comment]
I'll add unstructured to the requirements.txt
